In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
data = pd.read_csv('/kaggle/input/digit-recognizer/train.csv')


In [2]:
data = np.array(data)
m,n = data.shape
np.random.shuffle(data)

data_dev = data[0:1000].T
Y_dev = data_dev[0]
X_dev = data_dev[1:n]
X_dev = X_dev / 255.

train_dev = data[1000:m].T
Y_train = train_dev[0]
X_train = train_dev[1:n]
X_train = X_train/255.

In [3]:
Y_train

array([3, 0, 4, ..., 1, 1, 2])

In [4]:
def init_params():
    W1 = np.random.rand(10,784) - 0.5
    B1 = np.random.rand(10,1)-0.5
    W2 = np.random.rand(10,10)-0.5
    B2 = np.random.rand(10,1)-0.5
    return W1,B1,W2,B2
def ReLU(Z):
    return np.maximum(Z,0)
def softmax(Z):
    A = np.exp(Z) / sum(np.exp(Z))
    return A
def ReLU_dev(Z):
    return Z > 0
def one_hot(Y):
    one_hot = np.zeros((Y.size,Y.max()+1))
    one_hot[np.arange(Y.size),Y]=1
    one_hot = one_hot.T
    return one_hot
def forward_prop(W1,B1,W2,B2,X):
    Z1 = W1.dot(X) + B1
    A1 = ReLU(Z1)
    Z2 = W2.dot(A1) +B2
    A2 = softmax(Z2)
    return Z1,A1,Z2,A2

def backward_prop(Z1,Z2,W1,W2,A1,A2,X,Y):
    one_hot_y = one_hot(Y)
    dZ2 = A2 - one_hot_y
    dW2 = 1/m * (dZ2 .dot(A1.T) )
    dB2 = 1/m * dZ2
    dZ1 = W2.T.dot(dZ2)*ReLU_dev(Z1)
    dW1 = 1/m * (dZ1.dot(X.T))
    dB1 = 1/m * np.sum(dZ1)
    return dW2,dB2,dW1,dB1
def update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha):
    W1 = W1 - alpha * dW1
    b1 = b1 - alpha * db1    
    W2 = W2 - alpha * dW2  
    b2 = b2 - alpha * db2    
    return W1, b1, W2, b2

    
    

In [5]:
def get_pred(A2):
    return np.argmax(A2,0)
def get_acc(pred,Y):
    print(pred, Y)
    return np.sum(pred==Y)/Y.size
def gradient_Descent(X,Y,alpha,iterations):
    W1,B1,W2,B2 = init_params()
    for i in range(iterations):
        Z1,A1,Z2,A2 = forward_prop(W1,B1,W2,B2,X)
        dw2,db2,dw1,db1 = backward_prop(Z1,Z2,W1,W2,A1,A2,X,Y)
        W1,B1,W2,B2 = update_params(W1,B1,W2,B2,dw1,db1,dw2,db2,alpha)
        if i%10==0:
            print(f"iterations , {i}")
            pred = get_pred(A2)
            print("accuracy : ",get_acc(pred,Y))
    return W1,B1,W2,B2
            
        
        
        

In [6]:
W1, B1, W2, B2 = gradient_Descent(X_train, Y_train, 0.10, 500)

iterations , 0
[2 2 2 ... 2 6 2] [3 0 4 ... 1 1 2]
accuracy :  0.10063414634146342
iterations , 10
[2 2 4 ... 2 5 5] [3 0 4 ... 1 1 2]
accuracy :  0.15529268292682927
iterations , 20
[2 6 4 ... 2 2 6] [3 0 4 ... 1 1 2]
accuracy :  0.20729268292682926
iterations , 30
[2 0 4 ... 1 2 0] [3 0 4 ... 1 1 2]
accuracy :  0.26453658536585367
iterations , 40
[2 0 4 ... 1 2 0] [3 0 4 ... 1 1 2]
accuracy :  0.34339024390243905
iterations , 50
[5 0 4 ... 1 1 0] [3 0 4 ... 1 1 2]
accuracy :  0.39658536585365856
iterations , 60
[5 0 4 ... 1 1 0] [3 0 4 ... 1 1 2]
accuracy :  0.4365121951219512
iterations , 70
[5 0 4 ... 1 1 0] [3 0 4 ... 1 1 2]
accuracy :  0.47185365853658534
iterations , 80
[5 0 4 ... 1 1 0] [3 0 4 ... 1 1 2]
accuracy :  0.504219512195122
iterations , 90
[5 0 4 ... 1 1 6] [3 0 4 ... 1 1 2]
accuracy :  0.532609756097561
iterations , 100
[5 0 4 ... 1 1 2] [3 0 4 ... 1 1 2]
accuracy :  0.5580243902439025
iterations , 110
[5 0 4 ... 1 1 2] [3 0 4 ... 1 1 2]
accuracy :  0.580853658536585

In [7]:
W1.shape,b1.shape,W2.shape,b2.shape

NameError: name 'b1' is not defined

In [ ]:
def make_predictions(X, W1, b1, W2, b2):
    _, _, _, A2 = forward_prop(W1, b1, W2, b2, X)
    predictions = get_pred(A2)
    return predictions

def test_prediction(index, W1, b1, W2, b2):
    current_image = X_train[:, index, None]
    prediction = make_predictions(X_train[:, index, None], W1, b1, W2, b2)
    label = Y_train[index]
    print("Prediction: ", prediction)
    print("Label: ", label)
    
    current_image = current_image.reshape((28, 28)) * 255
    plt.gray()
    plt.imshow(current_image, interpolation='nearest')
    plt.show()

In [ ]:
test_prediction(0, W1, b1, W2, b2)
test_prediction(1, W1, b1, W2, b2)
test_prediction(2, W1, b1, W2, b2)
test_prediction(3, W1, b1, W2, b2)

In [ ]:
# dev_predictions = make_predictions(X_dev, W1, b1, W2, b2)
# get_accuracy(dev_predictions, Y_dev)